name: Build Flutter APK's and App bundle

on:
  push:
    branches:
      - master
    paths:
      - 'package-name.txt' # Specify the path to the package name file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Create 'apk' Folder if Not Exist
        run: mkdir -p apk

      - name: Check if package-name.txt has changed
        id: check-file-change
        run: |
          if git diff --quiet HEAD^ HEAD -- package-name.txt; then
            echo "File 'package-name.txt' has not changed. Skipping package name change."
            echo "::set-output name=changed::false"
          else
            echo "File 'package-name.txt' has changed. Proceeding with package name change."
            echo "::set-output name=changed::true"
          fi

      - name: Read data from a file
        if: steps.check-file-change.outputs.changed == 'true'
        run: |
          # Debug - Check Package Name File
          cat package-name.txt
        
          # Read the data from a file in your repository and store it as an environment variable
          export PACKAGE_NAME=$(<package-name.txt)
          echo "PACKAGE_NAME is set to: ${PACKAGE_NAME}"
          flutter pub run change_app_package_name:main $PACKAGE_NAME
          git add .
          git status
          git branch 
            
      - name: Build APK
        run: flutter build apk --split-per-abi --release

      - name: Move APK Files to 'apk' Folder
        run: mv build/app/outputs/apk/release/*.apk apk/

      - name: List Changed Files
        run: git status

      - name: List Staged Files
        run: git diff --cached --name-only

      - name: Commit APKs to Repository
        run: |
          git config user.name "Coder"
          git config user.email "gitCoder@example.com"
          git add apk/*.apk
          git commit -m "Add APK files"
          git push
