name: Build Flutter APK's and App bundle

on:
  push:
    branches:
      - master
    paths:
      - 'package-name.txt' # Specify the path to the package name file

jobs:
  change_package_name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if package-name.txt has changed
        id: check-file-change
        run: |
          if git diff --quiet HEAD^ HEAD -- package-name.txt; then
            echo "File 'package-name.txt' has not changed. Skipping package name change."
            echo "::set-output name=changed::false"
          else
            echo "File 'package-name.txt' has changed. Proceeding with package name change."
            echo "::set-output name=changed::true"
          fi

      - name: Read data from a file
        if: steps.check-file-change.outputs.changed == 'true'
        run: |
          # Read the data from a file in your repository and store it as an environment variable
          export PACKAGE_NAME=$(<package-name.txt)

      - name: Change Flutter App Package Name
        if: steps.check-file-change.outputs.changed == 'true'
        run: |
          # Use the stored environment variable to change the package name
          flutter pub run change_app_package_name:main $PACKAGE_NAME

  build:
    runs-on: ubuntu-latest
    needs: change_package_name

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v

      - name: Set up Gradle
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m" >> $GITHUB_WORKSPACE/android/gradle.properties

      - name: Checkout flutter_app code
        uses: actions/checkout@v2

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Create 'apk' Folder if Not Exist
        run: mkdir -p apk

      # Use a conditional check to skip these steps for specific tags
      - name: Build APK
        run: flutter build apk --debug

      - name: Move APK Files to 'apk' Folder
        run: mv build/app/outputs/flutter-apk/app-debug.apk apk/

  commit_and_push:
    runs-on: ubuntu-latest
    needs: [change_package_name, build]

    steps:
      - uses: actions/checkout@v2

      - name: Set Git User
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"

      - name: Check if package name has changed
        id: check-package-change
        run: |
          if [ -n "$PACKAGE_NAME" ]; then
            echo "Package name has changed."
            echo "::set-output name=package_changed::true"
          else
            echo "Package name has not changed."
            echo "::set-output name=package_changed::false"
          fi

      - name: Commit and Push Changes
        run: |
          if [[ ${{ steps.check-package-change.outputs.package_changed }} == 'true' ]]; then
            git add .
            git commit -m "Change package name to $PACKAGE_NAME"
          else
            git add apk/*.apk
            git commit -m "APK Generation"
          fi
          git push
