name: Build Flutter APK's and App bundle

on:
  push:
    branches:
      - master
    paths:
      - 'package-name.txt' # Specify the path to the package name file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v

      - name: Set up Gradle
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m" >> $GITHUB_WORKSPACE/android/gradle.properties

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Create 'apk' Folder if Not Exist
        run: mkdir -p apk

      - name: Check if package-name.txt has changed
        id: check-file-change
        run: |
          if git diff --quiet HEAD^ HEAD -- package-name.txt; then
            echo "File 'package-name.txt' has not changed. Skipping package name change."
            echo "::set-output name=changed::false"
          else
            echo "File 'package-name.txt' has changed. Proceeding with package name change."
            echo "::set-output name=changed::true"
          fi

      - name: Read data from a file
        if: steps.check-file-change.outputs.changed == 'true'
        run: |
          # Debug - List Repository Contents
          ls -R

          # Debug - Check Package Name File
          cat package-name.txt

          # Read the data from a file in your repository and store it as an environment variable
          export PACKAGE_NAME=$(<package-name.txt)

      - name: Change Flutter App Package Name
        if: steps.check-file-change.outputs.changed == 'true'
        run: |
          # Debug - Verify the PACKAGE_NAME variable
          echo "PACKAGE_NAME is set to: $PACKAGE_NAME"

          # Use the stored environment variable to change the package name
          flutter pub run change_app_package_name:main $PACKAGE_NAME

      - name: Build APK
        run: flutter build apk --debug

      - name: Move APK Files to 'apk' Folder
        run: mv build/app/outputs/flutter-apk/app-debug.apk apk/

  commit_and_push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check if package name has changed
        id: check-package-change
        run: |
          if [ -n "$PACKAGE_NAME" ]; then
            echo "Package name has changed."
            echo "::set-output name=package_changed::true"
          else
            echo "Package name has not changed."
            echo "::set-output name=package_changed::false"
          fi

      - name: List Changed Files
        run: git status

      - name: List Staged Files
        run: git diff --cached --name-only

      - name: Commit and Push Changes
        run: |
          git add .
          git status  # Added for debugging
          git diff --cached --name-only  # Added for debugging
          git commit -m "Change package name to $PACKAGE_NAME" || echo "No changes to commit"
          git push
