name: Build Flutter APK's and App bundle

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v

      - name: Set up Gradle
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m" >> $GITHUB_WORKSPACE/android/gradle.properties


      - name: Checkout flutter_app code
        uses: actions/checkout@v2

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Create 'apk' Folder if Not Exist
        run: mkdir -p apk

      - name: Build APK
        run: flutter build apk --release

      - name: Move APK Files to 'apk' Folder
        run: mv build/app/outputs/apk/release/*.apk apk/

      - name: Commit APKs to Repository
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"
          git add apk/*.apk
          git commit -m "Add APK files"
          git push

  access_apks:
    runs-on: ubuntu-latest

    steps:
      - name: Access 'apk' Folder and APKs
        run: |
          # Create 'apk' folder if it doesn't exist
          mkdir -p apk
          
          # Now you can access the 'apk' folder and APK files
          ls apk/
